### ISSUE TITLE
update_source no longer exists

### ISSUE THREAD

**Issue by javian** [nQuake/client-macosx#3]
Just tried to install nquake on a mac which resulted in
```
=== Cleaning up ===
* Renaming files...mv: rename /Users/user/Applications/nQuake/ezquake/sb/update_sources.bat to /Users/user/Applications/nQuake/ezquake/sb/update_sources: No such file or directory
done
* Removing Windows specific binaries...done
* Removing distribution files...done
* Making Mac OS X related updates..../install_nquake.sh: line 229: /Users/user/Applications/nQuake/ezquake/sb/update_sources: No such file or directory
./install_nquake.sh: line 230: /tmp/.nquake.tmp: No such file or directory
done
```
has the file been removed from the distribution ?

**Comment by liback** [comment]
It's not in the distribution files and the other installers (Win/Linux) don't have this step. However i guess it shouldn't be needed anyway as default nQuake config is set to use Quakeservers.net master server (among others) which is already in ezquake.pk3/sb/sources.txt so server browser functionality should still be good.

I'm leaning towards updating the install script to remove the update_sources steps.

**Comment by javian** [comment]
I made a pr for it.

**Comment by liback** [comment]
Thanks for the contribution, much appreciated!

**Comment by javian** [comment]
No problem, it was quick enough =)
